apiVersion: v1
kind: ReplicationController
metadata:
 name: myonlinestore-rc
spec:
  replicas: 2
  selector:
    app: myonlinestore-rc
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myonlinestore-rc
        version: 2.6.1
    spec:
      containers:
      - name:  myonlinestore-container
        image: dockerprasanth/myprasanth12mar22:1
        ports:
        - containerPort: 8080