apiVersion: v1
kind: ReplicationController
metadata:
 name: mynignx-rc
spec:
  replicas: 3
  selector:
    app: mynignx
  template:
    metadata:
      labels:
        app: mynignx  
    spec:
      containers:
      - name:  nginx-container
        image: nginx
        ports:
        - containerPort: 80