apiVersion: v1
kind: Service
metadata:
 name: mynignx-svc
 labels: 
  app: mynignx
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
      app:  myonlinestore
  